# Generated by Django 3.2 on 2023-04-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230416_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tilte',
            new_name='title',
        ),
    ]
