# Generated by Django 3.2 on 2023-04-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг жанра')),
            ],
        ),
    ]
